// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAliVcyk1LIdJgbVf6VMVF6G8U0Vw0ess',
    appId: '1:622373908016:web:9891c917749469fb2987f5',
    messagingSenderId: '622373908016',
    projectId: 'image-3d945',
    authDomain: 'image-3d945.firebaseapp.com',
    storageBucket: 'image-3d945.appspot.com',
    measurementId: 'G-JW60FW13Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2CuBCgrLPr_cZ66ESKswdfsjA-nuzoeM',
    appId: '1:622373908016:android:6b40efca69970c6b2987f5',
    messagingSenderId: '622373908016',
    projectId: 'image-3d945',
    storageBucket: 'image-3d945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAERKGp6e_xWlpgS_xG5L0MfsOQ_-vBfBk',
    appId: '1:622373908016:ios:95e85b62112a9c6a2987f5',
    messagingSenderId: '622373908016',
    projectId: 'image-3d945',
    storageBucket: 'image-3d945.appspot.com',
    iosBundleId: 'com.example.imageTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAliVcyk1LIdJgbVf6VMVF6G8U0Vw0ess',
    appId: '1:622373908016:web:6638eb2bf33255af2987f5',
    messagingSenderId: '622373908016',
    projectId: 'image-3d945',
    authDomain: 'image-3d945.firebaseapp.com',
    storageBucket: 'image-3d945.appspot.com',
    measurementId: 'G-F4LRC8TGGC',
  );
}
